### ISSUE TITLE
Unable to setup integration; cannot import name 'PredictionBase'

### ISSUE THREAD

**Issue by jkaberg** [elden1337/hass-peaq#139]
When trying to setup the integration the following exception is thrown at console

```
hast_1          | 2022-08-12 11:24:36 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration peaqev: cannot import name 'PredictionBase' from 'peaqevcore.services.prediction.prediction' (/usr/local/lib/python3.10/site-packages/peaqevcore/services/prediction/prediction.py)
```

hass-peaq: 1.6.1
hass: 2022.7.7

Should this be `Prediction` @ https://github.com/elden1337/peaqev-core/blob/main/Peaqevcore/services/prediction/prediction.py#L7 and https://github.com/elden1337/hass-peaq/blob/main/custom_components/peaqev/peaqservice/prediction/prediction.py#L3?

**Comment by elden1337** [comment]
Hope this helps. It did on my instance.
https://github.com/elden1337/hass-peaq/releases/tag/v1.7.0
