### ISSUE TITLE
Support multiple chargers

### ISSUE THREAD

**Issue by uphillbattle** [elden1337/hass-peaq#153]
I am in the process of having a second Easee charger installed. Does the Peaqev integration support addition of a second charger, and will it be possible to set schedules for each individual charger?

**Comment by elden1337** [comment]
It currently does not allow for more than one charger per installation. 
This could of course be changed, but some fixes to coding need to be planned.

**Comment by elden1337** [comment]
- [ ] Allow multiple chargers of same type
- [ ] Allow multiple chargers of different type
- [ ] Simulataneous charging capability
