### ISSUE TITLE
Chargepoint ID

### ISSUE THREAD

**Issue by nsimb** [elden1337/hass-peaq#16]
I feel really stupid but i cant get it to work, my guess is that i give the wrong Chargepoint ID
Tried all kind of stuff related to device and entitys

Checked out the code to see what it could be related to and tested. Sadly no luck

Easee charger, device is called 42 but i tried with different entitys aswell without luck
I asume that the power sensor should the the full entity name and mesure in W since power. Have a few but so far no luck

![image](https://user-images.githubusercontent.com/34156112/163817680-70b2c920-b3a5-4034-a441-724fbaee8928.png)

**Comment by elden1337** [comment]
It s a bug in the config validation. Think i just patched it in latest release.

**Comment by nsimb** [comment]
works fine thanks

**Comment by elden1337** [comment]
Make sure to update to latest. 
Have had a dance with latest HA tonight and the previous releases dont work in the latest HA.
