### ISSUE TITLE
get_average_kwh_price_core could not be calculated: division by zero

### ISSUE THREAD

**Issue by rawrgit** [elden1337/hass-peaq#176]
Found this warning flooding my logs every 5 seconds. Known issue?

This error originated from a custom integration.

Logger: peaqevcore.services.hourselection.hoursselection
Source: custom_components/peaqev/sensors/money_sensor.py:41
Integration: peaqev ev-charging (documentation, issues)
First occurred: 07:03:40 (5542 occurrences)
Last logged: 13:13:11

get_average_kwh_price_core could not be calculated: division by zero

**Comment by elden1337** [comment]
Not known afaik. Which version are you running? And do you have price-awareness active?

**Comment by rawrgit** [comment]
Did update to the latest (the one you put out about an hour ago) and it seems like those logs stopped flooding.

Yes, I do have price-awareness active.

**Comment by elden1337** [comment]
Ok cool. Then I hope it shall not return
