### ISSUE TITLE
Impossible to download from HACS

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaq#302]
Great plugin!

Problem is it doesn't seem possible to download with HACS, and the latest version seems to be 2.0.0. I guess that "main" is the latest?

[Screencast from 2023-10-18 15:20:04.webm](https://github.com/elden1337/hass-peaq/assets/4511254/04a07bd2-66db-4340-9008-0a3341f8bfea)

**Comment by enoch85** [comment]
> Hmm, cant seem to load your video (on mobile now) but i do see the later ones. Which HA-version are you running?

It's a fresh install with HAOS 11.

**Comment by elden1337** [comment]
now i can see the video. you are attempting to download peaqhvac (another repo for nibe pump). is that the intention?

**Comment by enoch85** [comment]
Aah, sorry, don't know. Isn't that the same? The Github badge led me here.

**Comment by elden1337** [comment]
Ah ok. Gotta update in that repo. But then the ev-integration (this) is not what you want. 
Peaqhvac should be at 2.2.0, but i did see failed deployment jobs so gotta check on that.

**Comment by enoch85** [comment]
OK, great, thanks!
