### ISSUE TITLE
Feature request: Skånska Energi

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaq#307]
Just wanted to add Skånska Energi to the mix of available net owners, if possible?

**Comment by elden1337** [comment]
I cant find any effektavgift (peak energy charges) on their consumer subscriptions. I only add those for calculations of peak avoidances. 
Have they announced a coming change to the model?

**Comment by enoch85** [comment]
> I cant find any effektavgift (peak energy charges) on their consumer subscriptions. I only add those for calculations of peak avoidances. Have they announced a coming change to the model?

No they don't have that and nothing that I'm aware of is coming. I thought the different energy providers list were current transfer fees, but I guess I was wrong.

**Comment by elden1337** [comment]
no, this is not accounted for, that's not how the integration works. 
transfer fees can be added either as a template from nordpool or (i think) in energidatasaervice by default?

**Comment by enoch85** [comment]
> no, this is not accounted for, that's not how the integration works. transfer fees can be added either as a template from nordpool or (i think) in energidatasaervice by default?

I actually created a helper for it. Just thought getting them automatically was more convenient.

Will switch to Greenly soon, and they have their own app were everything is included. So I think I will use [this integration](https://github.com/linsvensson/sensor.greenely) to fetch the actual price + my helper variables. 

I guess this can be closed.
