### ISSUE TITLE
Add updatecurrent to zaptec

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaq#320]
https://github.com/custom-components/zaptec/blob/master/custom_components/zaptec/number.py

seems to be a number-service with two variants to call. probably set both min and max to the same value to control it.

_also, in this, look at refactoring the installation for zaptec since there's been a breaking change for entities which may crash peaqev-setup for it._

**Comment by andersop91** [comment]
Hi - first of all your work looks very promising. Currently seems to be just what I'm looking for in one package!
I found this issue interesting as I also have a Zaptec Go charger. 

I guess this is what you're looking for: 
https://github.com/custom-components/zaptec?tab=readme-ov-file#setting-charging-current

![image](https://github.com/elden1337/hass-peaq/assets/57915164/1dbe6de0-0c30-4721-afd9-8799190bf260)
