### ISSUE TITLE
Stopped until further notice

### ISSUE THREAD

**Issue by pezlin** [elden1337/hass-peaq#331]
Quite often I see that the status of peaqev is Stopped until further notice. It can be at any time of the day. A restart of HA is the only way to solve it that I have found. A reload of the integration does not solve it. Today I noticed the status after plugging in the charger cable in the car at around 16. This issue started to occur about a month or so back. How to troubleshoot?

**Comment by pezlin** [comment]
I have the setting to always charge below 60 öre and the price yesterday was lower at that point and forward. Have I set the setting för always charge incorrectly perhaps?![image](https://github.com/elden1337/hass-peaq/assets/47033099/60548c2b-4977-4639-8bb1-e0147c43c888)

**Comment by elden1337** [comment]
Sounds like a bug. Im gonna do a test case and see what i get, hopefully during the weekend? Which price area do you live in so i can match the correct prices?

**Comment by elden1337** [comment]
Havent found any obvious bug yet. Continue looking. 
Next time this happens please comment here so that i know that day's prices. 
Also test changing your cautiontype to Suave and see if it helps.

**Comment by elden1337** [comment]
Closing this as i haven't found any other reason in the code. Please reopen with new info if necessary.
