### ISSUE TITLE
Configuration fails at setup of price aware charging

### ISSUE THREAD

**Issue by JonathanJorstad** [elden1337/hass-peaq#347]
After updating to 3.6.1 my previous setup/hub did not work, so I tried to configure a new one, i.e. add peaqev from scratch. I manage to specify the power sensor, selecting charger brand (Zaptec) and grid company (Glitre). But when I do not want price aware charing in the next step, I get the error "unknown error occurred" whatever I specify. I have not tried to add a price service. I have re-downloaded peaqev in hacs and restarted HA as promted.
![image](https://github.com/elden1337/hass-peaq/assets/152968084/ed376766-64fe-4934-9806-463f2c56e1d9)

**Comment by elden1337** [comment]
If you are able to dump logs here it would help error search.

**Comment by JonathanJorstad** [comment]
Since the setup fails, the integration is not listed under Settings > Devices & Services > Integrations, so it is not possible to enable debug logging. However, I attach the HA system log
[home-assistant_2024-07-07T15-00-46.102Z.log](https://github.com/user-attachments/files/16119770/home-assistant_2024-07-07T15-00-46.102Z.log)

**Comment by elden1337** [comment]
think i caught it by the help of a another stranded user. pushing a fix soon which hopefully will help. otherwise we'll iterate further on it.

**Comment by elden1337** [comment]
https://github.com/elden1337/hass-peaq/releases/tag/3.6.2

Please close this issue if problem goes away, otherwise comment what you get as error.

**Comment by JonathanJorstad** [comment]
Confirmed working

søn. 7. juli 2024, 18:04 skrev Magnus Eldén ***@***.***>:
