### ISSUE TITLE
Hacs installation of latest beta refers to configuration not GUI

### ISSUE THREAD

**Issue by nsimb** [elden1337/hass-peaq#39]
Any example on how to set this up in conifguration since I am getting this error in lastest beta in v0.4.2-rev2

![image](https://user-images.githubusercontent.com/34156112/165524338-f5ba0121-7981-46cb-a2b2-15499e2e25bd.png)

**Comment by elden1337** [comment]
Weird. And i guess you rebooted after upgrade? 
Had another guy installing this vers earlier without issues. 

Does logs say anything about it?

**Comment by elden1337** [comment]
Actually. Lets move this discussion to the beta disc. 
Maybe more people have the same issue. 

https://github.com/elden1337/hass-peaq/discussions/38

**Comment by elden1337** [comment]
new beta-release is out: https://github.com/elden1337/hass-peaq/releases/tag/v0.5.0-beta.3

**Comment by nsimb** [comment]
tested with the latest beta now and instead of the previus error it spins for a long time then gives 
But lets take that in the beta thread, and will allso do a clean installation before posting there
So closing this thread


![image](https://user-images.githubusercontent.com/34156112/165900542-e3175249-448f-4c1f-80fb-6fb7c14168a8.png)
