### ISSUE TITLE
OpenEVSE

### ISSUE THREAD

**Issue by lundan** [elden1337/hass-peaq#59]
**Info:** https://www.openevse.com/
**API documentation:** https://openevse.stoplight.io/docs/openevse-wifi-v4/

**Comment by elden1337** [comment]
If you intend to PR this i should mention that i aim to move the chargertypes to the core project (for reuseability in other platforms than HA in the future)

**Comment by elden1337** [comment]
https://www.home-assistant.io/integrations/openevse/
