### ISSUE TITLE
Own Energy Production

### ISSUE THREAD

**Issue by stejo388** [elden1337/hass-peaq#82]
Hi,
To make this integration even better my suggestion is to take into account own energy production.  For me that has solar panel it´s cheapest to charge the car when they produce energy independent on the hourly price at that moment.

To make it even more advanced you could look at the forecast to plan ahead.

**Comment by elden1337** [comment]
Thank you. Have been thinking about this as well. 

There will probably have to be a setting for:

- Always favor charging on prod
- Favor charging if spotprice < x
- Delay charging if projected prod later today (as you mention). Etc.  

This will most def be a set of features, an epic. 

Do you code? If so would you like to help out?

This will touch both this repo and the core-repo i'm making for this.

**Comment by stejo388** [comment]
Hi,

Sorry I have not really coded for 15 years so I don´t think you would like to have my help :) But I´m glad to help you trying and discussing the topic.

**Comment by elden1337** [comment]
Cool. More people have started to gather around this repo now which is awesome, so perhaps someone else will take on this (faster delivery than just me coding). 

Ill start when i have time to split this into stories. 

I guess you have your production visible in HA then so peaq can see it?!

**Comment by andreasropel** [comment]
Yes, you can see the forecast through the forecast.solar integration in HA. It creates sensor(s) for today and tomorrow.

**Comment by elden1337** [comment]
- [ ]  #83
- [ ]   #84
